=== akash-suresh-kumar/data-quality-assessment/schemas/schema_TransitManagement.json
{
	"$id": "https://voc.iudx.org.in/TransitManagement",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"location": {
			"type": "object",
			"properties": {
				"coordinates": {
					"type": "array",
					"items": {
						"type": "number"
					}
				}
			}
		},
		"last_stop_id": {
			"type": "string"
		},
		"actual_trip_start_time": {
			"type": "string",
			"format": "date-time"
		},
		"speed": {
			"type": "number"
		},
		"vehicle_label": {
			"type": "string"
		},
		"observationDateTime": {
			"type": "string",
			"format": "date-time"
		},
		"trip_delay": {
			"type": "number"
		},
		"trip_direction": {
			"type": "string"
		},
		"last_stop_arrival_time": {
			"type": "string"
		},
		"route_id": {
			"type": "string"
		},
		"license_plate": {
			"type": "string"
		},
		"trip_id": {
			"type": "string"
		}
	},
	"required": ["id", "location", "last_stop_id", "actual_trip_start_time", "speed", "vehicle_label", "observationDateTime", "trip_delay", "trip_direction", "last_stop_arrival_time", "route_id", "license_plate", "trip_id"],
	"additionalProperties": false
}

=== akash-suresh-kumar/data-quality-assessment/data/surat_live_bus_eta_data.json
[
        {
            "vehicle_label": "M22",
            "last_stop_id": "4022",
            "route_id": "11U",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:29:25",
            "location": {
                "coordinates": [
                    72.848299,
                    21.146356
                ],
                "type": "Point"
            },
            "speed": 17.0,
            "observationDateTime": "2021-05-08T08:29:45+05:30",
            "trip_id": "16004236",
            "license_plate": "GJ05BX3216",
            "trip_delay": 36,
            "actual_trip_start_time": "2021-05-08T08:20:46+05:30",
            "trip_direction": "UP"
        },
        {
            "vehicle_label": "M28",
            "last_stop_id": "4028",
            "route_id": "11D",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:29:21",
            "location": {
                "coordinates": [
                    72.859182,
                    21.116843
                ],
                "type": "Point"
            },
            "speed": 18.0,
            "observationDateTime": "2021-05-08T08:29:51+05:30",
            "trip_id": "16004361",
            "license_plate": "GJ05BX3239",
            "trip_delay": 7,
            "actual_trip_start_time": "2021-05-08T08:26:51+05:30",
            "trip_direction": "DN"
        },
        {
            "vehicle_label": "M49",
            "last_stop_id": "2041",
            "route_id": "11D",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:28:39",
            "location": {
                "coordinates": [
                    72.833627,
                    21.178609
                ],
                "type": "Point"
            },
            "speed": 17.0,
            "observationDateTime": "2021-05-08T08:29:50+05:30",
            "trip_id": "16004326",
            "license_plate": "GJ05BX3416",
            "trip_delay": 127,
            "actual_trip_start_time": "2021-05-08T08:12:48+05:30",
            "trip_direction": "DN"
        },
        {
            "vehicle_label": "M53",
            "last_stop_id": "4027",
            "route_id": "11U",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:24:55",
            "location": {
                "coordinates": [
                    72.860109,
                    21.114961
                ],
                "type": "Point"
            },
            "speed": 29.0,
            "observationDateTime": "2021-05-08T08:26:29+05:30",
            "trip_id": "16004191",
            "license_plate": "GJ05BX3438",
            "trip_delay": 131,
            "actual_trip_start_time": "2021-05-08T08:09:07+05:30",
            "trip_direction": "UP"
        },
        {
            "vehicle_label": "M60",
            "last_stop_id": "2047",
            "route_id": "11U",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:29:02",
            "location": {
                "coordinates": [
                    72.847256,
                    21.149716
                ],
                "type": "Point"
            },
            "speed": 38.0,
            "observationDateTime": "2021-05-08T08:29:47+05:30",
            "trip_id": "16004281",
            "license_plate": "GJ05BX3508",
            "trip_delay": 26,
            "actual_trip_start_time": "2021-05-08T08:21:28+05:30",
            "trip_direction": "UP"
        },
        {
            "vehicle_label": "M69",
            "last_stop_id": "4031",
            "route_id": "11D",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": null,
            "location": {
                "coordinates": [
                    72.865129,
                    21.103205
                ],
                "type": "Point"
            },
            "speed": 0.0,
            "observationDateTime": "2021-05-08T08:29:57+05:30",
            "trip_id": "16004343",
            "license_plate": "GJ05BX3862",
            "trip_delay": 1212,
            "actual_trip_start_time": "2021-05-08T08:18:34+05:30",
            "trip_direction": "DN"
        },
        {
            "vehicle_label": "M22",
            "last_stop_id": "4022",
            "route_id": "11U",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:29:25",
            "location": {
                "coordinates": [
                    72.848551,
                    21.144395
                ],
                "type": "Point"
            },
            "speed": 13.0,
            "observationDateTime": "2021-05-08T08:30:10+05:30",
            "trip_id": "16004236",
            "license_plate": "GJ05BX3216",
            "trip_delay": 37,
            "actual_trip_start_time": "2021-05-08T08:20:46+05:30",
            "trip_direction": "UP"
        },
        {
            "vehicle_label": "M28",
            "last_stop_id": "4028",
            "route_id": "11D",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:29:21",
            "location": {
                "coordinates": [
                    72.85876,
                    21.117956
                ],
                "type": "Point"
            },
            "speed": 34.0,
            "observationDateTime": "2021-05-08T08:30:11+05:30",
            "trip_id": "16004361",
            "license_plate": "GJ05BX3239",
            "trip_delay": 3,
            "actual_trip_start_time": "2021-05-08T08:26:51+05:30",
            "trip_direction": "DN"
        },
        {
            "vehicle_label": "M49",
            "last_stop_id": "2041",
            "route_id": "11D",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:28:39",
            "location": {
                "coordinates": [
                    72.832844,
                    21.17985
                ],
                "type": "Point"
            },
            "speed": 36.0,
            "observationDateTime": "2021-05-08T08:30:10+05:30",
            "trip_id": "16004326",
            "license_plate": "GJ05BX3416",
            "trip_delay": 125,
            "actual_trip_start_time": "2021-05-08T08:12:48+05:30",
            "trip_direction": "DN"
        },
        {
            "vehicle_label": "M53",
            "last_stop_id": "4027",
            "route_id": "11U",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:24:55",
            "location": {
                "coordinates": [
                    72.860109,
                    21.114961
                ],
                "type": "Point"
            },
            "speed": 29.0,
            "observationDateTime": "2021-05-08T08:26:29+05:30",
            "trip_id": "16004191",
            "license_plate": "GJ05BX3438",
            "trip_delay": 131,
            "actual_trip_start_time": "2021-05-08T08:09:07+05:30",
            "trip_direction": "UP"
        },
        {
            "vehicle_label": "M60",
            "last_stop_id": "2047",
            "route_id": "11U",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:29:02",
            "location": {
                "coordinates": [
                    72.847708,
                    21.149292
                ],
                "type": "Point"
            },
            "speed": 40.0,
            "observationDateTime": "2021-05-08T08:29:52+05:30",
            "trip_id": "16004281",
            "license_plate": "GJ05BX3508",
            "trip_delay": 22,
            "actual_trip_start_time": "2021-05-08T08:21:28+05:30",
            "trip_direction": "UP"
        },
        {
            "vehicle_label": "M69",
            "last_stop_id": "4031",
            "route_id": "11D",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": null,
            "location": {
                "coordinates": [
                    72.865129,
                    21.103205
                ],
                "type": "Point"
            },
            "speed": 0.0,
            "observationDateTime": "2021-05-08T08:30:12+05:30",
            "trip_id": "16004343",
            "license_plate": "GJ05BX3862",
            "trip_delay": 1202,
            "actual_trip_start_time": "2021-05-08T08:18:34+05:30",
            "trip_direction": "DN"
        },
        {
            "vehicle_label": "M22",
            "last_stop_id": "4022",
            "route_id": "11U",
            "id": "suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-realtime-info/surat-itms-live-eta",
            "last_stop_arrival_time": "08:29:25",
            "location": {
                "coordinates": [
